name: "GitHub main workflow"

on:
  pull_request:
    branches:
      - main

jobs:
   update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
            output_file_paths: '[./README.md]'
            categories: '[code-block]'
